### DISCUSSION TITLE
ERR_TOO_MANY_REDIRECTS when using behind Nginx reverse proxy with SSL termination

### DISCUSSION THREAD

**Discussion by artinflight** [chrisvel/tududi#244] [Feature requests]
Hello! I'm trying to set up Tududi using your Docker image (chrisvel/tududi:latest) on an ARM64 device (Raspberry Pi 4) and am running into a persistent ERR_TOO_MANY_REDIRECTS loop when accessing it through my Nginx reverse proxy. I've been following your documentation and have tried numerous configurations without success. I would be very grateful for any insight or help!

Here is a complete summary of my setup and the issue:

Goal:
Access Tududi via https://todo.local through an Nginx reverse proxy that handles SSL termination.

Current State:
The Tududi container starts successfully and the logs show the Puma server listening on http://0.0.0.0:9292.

When accessing https://todo.local, the browser gets stuck in a redirect loop and eventually fails with ERR_TOO_MANY_REDIRECTS.

Tududi logs show a continuous loop of 302 redirects for /login.

My Configuration Files:
1. docker-compose.yml for Tududi:
(Note: I am using separate compose files for my services, all connected to the same external Docker network app_network)
```
# ~/docker/network/tududi-compose.yml
services:
  tududi:
    image: chrisvel/tududi:latest
    container_name: tududi
    restart: unless-stopped
    volumes:
      - ./tududi_db:/usr/src/app/db
    environment:
      TZ: America/Toronto
      TUDUDI_INTERNAL_SSL_ENABLED: 'false'
      TUDUDI_USER_EMAIL: 'MY_EMAIL_ADDRESS' # Actual email address is used
      TUDUDI_USER_PASSWORD: 'MY_SECURE_PASSWORD' # Actual password is used
      TUDUDI_SESSION_SECRET: 'MY_GENERATED_SECRET' # Actual secret is used
      TUDUDI_ALLOWED_ORIGINS: 'https://todo.local,http://tududi:9292'
    networks:
      - app_network

networks:
  app_network:
    external: true
```
2. Nginx Reverse Proxy Config (todo.local.conf):
(This file is located in /etc/nginx/conf.d/ inside the Nginx container)
```
# Redirect HTTP requests to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name todo.local;
    return 301 https://$host$request_uri;
}

# Main HTTPS server block
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name todo.local;

    # SSL certs are self-signed by a custom CA, which is trusted on client devices
    ssl_certificate /etc/nginx/ssl/todo.local.crt;
    ssl_certificate_key /etc/nginx/ssl/todo.local.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location / {
        proxy_pass http://tududi:9292;

        # Headers exactly as specified in the Tududi GitHub README
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_set_header X-Forwarded-Port 443;
        proxy_redirect off;
    }
}
```
Troubleshooting Steps Already Taken:
I have confirmed the application starts and listens on port 9292. The redirect loop persists even after trying the following:

Using the exact proxy_set_header directives from the documentation's Nginx example.

Adding the RAILS_FORCE_SSL: 'true' environment variable.

Using an upstream block and explicit resolver 127.0.0.11; in Nginx.

Summary of the Problem:
The Tududi application does not seem to be correctly respecting the X-Forwarded-Proto, X-Forwarded-Ssl, or X-Forwarded-Port headers and continues to force an HTTPS redirect even when the connection is already secure via the proxy.

Could you please advise if there is a different environment variable or Nginx configuration required for this image to work correctly behind a reverse proxy that handles SSL termination?

Thank you for your time and for the great application!
