### ISSUE TITLE
v0.50.0 database file creation problem

### ISSUE THREAD

**Issue by labrown** [chrisvel/tududi#85]
I'm trying out tududi for the first time and have run into an issue with startup.

After reading the other recent sqlite issues I realized the db file now lives in /app/backend/db so I adjusted my volume mount to that location.
Then I started getting this error:
```
$ docker compose up -d tududi && docker logs tududi -f
[+] Running 1/1
 ✔ Container tududi  Started                                                                                                                                         0.6s 
❌ SQLITE_CANTOPEN: unable to open database file
```
with the following docker compose.yml:
```
  tududi:
    image: chrisvel/tududi:latest
    restart: unless-stopped
    container_name: tududi
    environment:
      - TUDUDI_USER_EMAIL=user@example.com
      - TUDUDI_USER_PASSWORD=${TUDUDI_USER_PASSWORD}
      - TUDUDI_SESSION_SECRET="${TUDUDI_SESSION_SECRET}"
      - TUDUDI_INTERNAL_SSL_ENABLED=false
      - TUDUDI_ALLOWED_ORIGINS=https://tududi.${LAB_DOMAIN}

    volumes:
      - ./config/tududi:/app/backend/db
    ports:
      - 3002        
```
Checking out `./config/tududi` I see that it is owned by root, which I think is the problem.

```
$ ls -ld ./config/tududi
drwxr-xr-x 2 root root 4096 Jun 26 00:55 ./config/tududi
$ 
```
If I change the ownership of `./config/tududi` to 1001:1001, the user inside the docker container, then the container spins up properly.

```
$ sudo chown 1001:1001 ./config/tududi
$ docker compose up tududi
[+] Running 1/1
 ✔ Container tududi  Created                                                                                                                                         0.0s 
Attaching to tududi
tududi  | ✅ DB ready
tududi  | ✅ User created
tududi  | Loaded 20 quotes from configuration
tududi  | (sequelize) Warning: Unknown attributes (password) passed to defaults option of findOrCreate
tududi  | Server running on port 3002
tududi  | Server listening on http://localhost:3002
tududi  | 127.0.0.1 - - [26/Jun/2025:05:03:54 +0000] "GET /api/health HTTP/1.1" 200 102 "-" "curl/8.14.1"
```
Everything works correctly if I pre-create `./config/tududi` and `chown 1001:1001 ./config/tududi` before running my `docker compose up tududi`.  I'm thinking this has to do with how volume mounts get created by docker when the source directory doesn't exist already.
