### ISSUE TITLE
Blank page on startup, https referenced even though turned off?

### ISSUE THREAD

**Issue by sottey** [chrisvel/tududi#86]
Running with this docker compose:
```
services:
  tududi:
    environment:
      - TUDUDI_USER_EMAIL=[MYEMAILISHERE]
      - TUDUDI_USER_PASSWORD=[MYUSERPASSWORDISHERE]
      - TUDUDI_INTERNAL_SSL_ENABLED=false
      - TUDUDI_ALLOWED_ORIGINS=""
      - TUDUDI_SESSION_SECRET=[MYSESSIONSECRETISHERE]
    volumes:
      - /home/myusernameishere/docker-data/tududi-data/db:/usr/etc/app/backend/db
    ports:
      - 8083:3002
    image: chrisvel/tududi:latest
networks: {}
```

Startup shows this:
```
tududi-1  | ✅ DB ready
tududi-1  | ✅ User created
tududi-1  | Loaded 20 quotes from configuration
tududi-1  | (sequelize) Warning: Unknown attributes (password) passed to defaults option of findOrCreate
tududi-1  | Server running on port 3002
tududi-1  | Server listening on http://localhost:3002
tududi-1  | 127.0.0.1 - - [26/Jun/2025:14:40:34 +0000] "GET /api/health HTTP/1.1" 200 102 "-" "curl/8.14.1"
tududi-1  | 192.168.7.152 - - [26/Jun/2025:14:40:36 +0000] "GET / HTTP/1.1" 200 267 "http://[myiphere]:8081/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15"
tududi-1  | 127.0.0.1 - - [26/Jun/2025:14:41:34 +0000] "GET /api/health HTTP/1.1" 200 103 "-" "curl/8.14.1"
tududi-1  | 127.0.0.1 - - [26/Jun/2025:14:42:34 +0000] "GET /api/health HTTP/1.1" 200 104 "-" "curl/8.14.1"
tududi-1  | 127.0.0.1 - - [26/Jun/2025:14:43:34 +0000] "GET /api/health HTTP/1.1" 200 104 "-" "curl/8.14.1"
```

Console shows this:

![Image](https://github.com/user-attachments/assets/3e8e57bf-327a-442c-ac11-f1999550c32e)

It seems like, even though I have  - TUDUDI_INTERNAL_SSL_ENABLED=false it is still, somewhere, using https
