### ISSUE TITLE
Docker: problems with file ownership for the `app` user

### ISSUE THREAD

**Issue by andreyfedoseev** [chrisvel/tududi#96]
I see that you recently updated the docker image to run the app as non-root user. I assume that was made to improve security.

My problem with that is that the `app` user that you create in the docker image has hardcoded UID and GID (`1001:1001`). 

In my case, I want to run the app on my home server.

I created a folder `/var/lib/tududi/db` (owned by `root`), and mounted that folder as volume to `/app/backend/db`. The application won't start because:

```
❌ ERROR: Database directory /app/backend/db is not writable by user app (1001:1001)
ℹ  If using Docker volumes, ensure the host directory has proper ownership:
   sudo chown -R 1001:1001 /host/path/to/db
```

Now, I could change the ownership of that folder to `1001:1001`. However, I already have a user with `UID=1001` on my host system, and I don't want that user to have access to app files.

**Comment by antanst** [comment]
Instead of changing ownership of the folder, you can build your own Docker image and use the `--build-arg` argument to specify custom APP_UID and APP_GID values, for example:

```shell
docker build --build-arg APP_UID=1005 --build-arg APP_GID=1005 -t tududi .
```

**Comment by andreyfedoseev** [comment]
I think I should have emphasized that this is a security problem, not a simple inconvenience.

How about that:

On a system with more than one regular user, the default docker image exposes the data files to the second account user on the host system which typically has UID=1001.

This issue is still unresolved.

Also, other projects use environment variables to specify custom UID and GID instead of the build arguments. They set UID/GID for the app user at runtime, either in the `ENTRYPOINT` script, or in some other script that runs when the container is started. See  https://github.com/paperless-ngx/paperless-ngx/blob/43abb0541bb2970627a9a00528a3b1ccd32abfc5/docker/rootfs/etc/s6-overlay/s6-rc.d/init-modify-user/run#L4 for example.

**Comment by Ravage2857** [comment]
Confirming the same issue.

**Comment by andreyfedoseev** [comment]
I checked the docker image `0.65` and it still doesn't work. Running the container with `-e APP_UID=... -e APP_GID` has no effect, the application still uses UID/GID=1001.

I checked the `Dockerfile`, it takes `APP_UID` and `APP_GID` from the build args, and uses them to create the app user. However, happens in build time, not in run time. I don't think that [the example in docker-compose.yml](https://github.com/chrisvel/tududi/blob/92f82e95c639a670dbd279bc185ee5dc6691f77c/docker-compose.yml#L11-L13) is accurate. I think add these env variables there won't do anything.

To fix that, you'll need an `ENTRYPOINT` script that will change UID/GID for the `app` user to the values specified in env variables when the container is started (see the example I gave above).

**Comment by sgrassie** [comment]
Here is my docker compose which works for me on my synology nas. The user `1029` is my docker user which has all relevant permissions to everything under `/volume2/docker`

```
services:
  tududi:
    image: chrisvel/tududi:latest
    container_name: Tududi
    volumes:
      - /volume2/docker/tududi/db:/app/backend/db
      - /volume2/docker/tududi/uploads:/app/backend/uploads
    user: "1029:100"
    environment:
      TUDUDI_USER_EMAIL: <email>
      TUDUDI_USER_PASSWORD: password1
      TUDUDI_SESSION_SECRET: $(openssl rand -hex 64)
      TUDUDI_INTERNAL_SSL_ENABLED: false
    ports:
      - 3002:3002
    restart: unless-stopped
```
